-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS crypto_db;

USE crypto_db;

-- Create the table 

DROP TABLE IF EXISTS crypto_market;

CREATE TABLE crypto_market (
    ID VARCHAR(255),
    SYMBOL VARCHAR(50),
    NAME VARCHAR(255),
    IMAGE_URL VARCHAR(500),
    CURRENT_PRICE DOUBLE,
    MARKET_CAP DOUBLE,
    MARKET_CAP_RANK INT,
    TOTAL_VOLUME DOUBLE,
    HIGH_24H DOUBLE,
    LOW_24H DOUBLE,
    PRICE_CHANGE_24H DOUBLE,
    PRICE_CHANGE_PERCENTAGE_24H DOUBLE,
    PRICE_CHANGE_7D DOUBLE,
    PRICE_CHANGE_30D DOUBLE,
    PRICE_CHANGE_1Y DOUBLE,
    MARKET_CAP_CHANGE_24H DOUBLE,
    TOTAL_SUPPLY DOUBLE,
    MAX_SUPPLY DOUBLE,
    ATH DOUBLE,
    ATL DOUBLE,
    ATH_DATE DATETIME,
    ATL_DATE DATETIME,
    FETCH_DATE DATETIME
);


-- Preview the table
SELECT * FROM crypto_market;
